# Generated by Django 5.1 on 2024-09-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FloorSheet',
            fields=[
                ('contract_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('stock_symbol', models.CharField(max_length=10)),
                ('buyer', models.IntegerField()),
                ('seller', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='ListedSecurities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('symbol', models.CharField(max_length=20)),
                ('status', models.CharField()),
                ('sector', models.CharField()),
                ('instrument', models.CharField()),
                ('email', models.CharField()),
                ('website', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='MarketSummary',
            fields=[
                ('business_date', models.DateField(primary_key=True)),  # Assuming you want to use business_date as the primary key
                ('nepse_index', models.DecimalField(decimal_places=2, max_digits=20)),
                ('sensitive_index', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_turnover', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_traded_shares', models.IntegerField()),
                ('total_transactions', models.IntegerField()),
                ('total_scripts_traded', models.IntegerField()),
            ],
        )
            ]
