# Generated by Django 5.1 on 2024-09-10 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listedsecurities',
            old_name='name',
            new_name='company_name',
        ),
    ]
