# Generated by Django 5.1 on 2024-09-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_name_listedsecurities_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listedsecurities',
            name='website',
            field=models.CharField(blank=True, null=True),
        ),
    ]
