# Generated by Django 5.1 on 2024-09-10 12:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_listedsecurities_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketsummary',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
