# Generated by Django 5.1 on 2024-09-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_marketsummary_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodaysPrices',
            fields=[
                ('business_date', models.DateTimeField(blank=True, null=True)),
                ('security_id', models.IntegerField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=20)),
                ('security_name', models.CharField(max_length=200)),
                ('open_price', models.DecimalField(decimal_places=1, max_digits=20)),
                ('high_price', models.DecimalField(decimal_places=1, max_digits=20)),
                ('low_price', models.DecimalField(decimal_places=1, max_digits=20)),
                ('close_price', models.DecimalField(decimal_places=1, max_digits=20)),
                ('total_traded_quantity', models.IntegerField()),
                ('total_traded_value', models.DecimalField(decimal_places=1, max_digits=20)),
                ('previous_day_close_price', models.DecimalField(decimal_places=1, max_digits=20)),
                ('fifty_two_weeks_high', models.DecimalField(decimal_places=1, max_digits=20)),
                ('fifty_two_weeks_low', models.DecimalField(decimal_places=1, max_digits=20)),
                ('last_updated_time', models.DateTimeField(blank=True, null=True)),
                ('last_updated_price', models.DecimalField(decimal_places=1, max_digits=20)),
                ('total_trades', models.IntegerField()),
                ('average_traded_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('market_capitalization', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
