# Generated by Django 5.1.1 on 2024-10-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_todaysprices"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllSecurities",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("company_name", models.CharField(max_length=255)),
                ("symbol", models.CharField(max_length=50)),
                ("security_name", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=1)),
                (
                    "company_email",
                    models.EmailField(blank=True, max_length=255, null=True),
                ),
                ("website", models.URLField(blank=True, max_length=255, null=True)),
                ("sector_name", models.CharField(max_length=255)),
                ("regulatory_body", models.CharField(max_length=255)),
                ("instrument_type", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="BrokerData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_pages", models.IntegerField()),
                ("last", models.BooleanField()),
                ("total_elements", models.IntegerField()),
                ("size", models.IntegerField()),
                ("number", models.IntegerField()),
                ("first", models.BooleanField()),
                ("number_of_elements", models.IntegerField()),
                ("empty", models.BooleanField()),
                ("pageable_sort_unsorted", models.BooleanField()),
                ("pageable_sort_sorted", models.BooleanField()),
                ("pageable_sort_empty", models.BooleanField()),
                ("pageable_offset", models.IntegerField()),
                ("pageable_page_number", models.IntegerField()),
                ("pageable_page_size", models.IntegerField()),
                ("pageable_paged", models.BooleanField()),
                ("pageable_unpaged", models.BooleanField()),
                ("sort_unsorted", models.BooleanField()),
                ("sort_sorted", models.BooleanField()),
                ("sort_empty", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="LiveIndices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.BigIntegerField()),
                ("value", models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name="LiveStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("security_id", models.IntegerField()),
                ("security_name", models.CharField(max_length=200)),
                ("symbol", models.CharField(max_length=20)),
                ("index_id", models.IntegerField()),
                ("open_price", models.DecimalField(decimal_places=2, max_digits=20)),
                ("high_price", models.DecimalField(decimal_places=2, max_digits=20)),
                ("low_price", models.DecimalField(decimal_places=2, max_digits=20)),
                ("total_trade_quantity", models.IntegerField()),
                (
                    "total_trade_value",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "last_traded_price",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "percentage_change",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("last_updated_datetime", models.DateTimeField()),
                ("last_traded_volume", models.IntegerField()),
                (
                    "previous_close",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "average_traded_price",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MarketCap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_date", models.DateField()),
                ("sen_mar_cap", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "sen_float_mar_cap",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                ("float_mar_cap", models.DecimalField(decimal_places=2, max_digits=20)),
                ("mar_cap", models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name="NepalListedSecurities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("symbol", models.CharField(max_length=20)),
                ("status", models.CharField(max_length=50)),
                ("sector", models.CharField(max_length=100)),
                ("instrument", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=100, null=True)),
                ("website", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SectorwiseSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_date", models.DateTimeField()),
                ("sector_name", models.CharField(max_length=100)),
                (
                    "turnover_values",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                ("turnover_volume", models.IntegerField()),
                ("total_transaction", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="TopGainer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=20)),
                ("ltp", models.DecimalField(decimal_places=2, max_digits=20)),
                ("point_change", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "percentage_change",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("security_name", models.CharField(max_length=200)),
                ("security_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="TopLoser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=20)),
                ("ltp", models.DecimalField(decimal_places=2, max_digits=20)),
                ("point_change", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "percentage_change",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("security_name", models.CharField(max_length=200)),
                ("security_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="TopTrades",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=20)),
                ("shares_traded", models.IntegerField()),
                ("closing_price", models.DecimalField(decimal_places=2, max_digits=20)),
                ("security_name", models.CharField(max_length=200)),
                ("security_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="TopTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("security_id", models.IntegerField()),
                ("total_trades", models.IntegerField()),
                (
                    "last_traded_price",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                ("security_name", models.CharField(max_length=200)),
                ("symbol", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="TopTurnover",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=20)),
                ("turnover", models.DecimalField(decimal_places=2, max_digits=20)),
                ("closing_price", models.DecimalField(decimal_places=2, max_digits=20)),
                ("security_name", models.CharField(max_length=200)),
                ("security_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="TradingAverage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("security_id", models.IntegerField()),
                ("symbol", models.CharField(max_length=20)),
                ("security_name", models.CharField(max_length=200)),
                (
                    "closing_price_average",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "total_traded_amount",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                ("total_traded_shares", models.IntegerField()),
                ("total_trades", models.IntegerField()),
                (
                    "weighted_average",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                ("close_price", models.DecimalField(decimal_places=2, max_digits=20)),
                ("closing_date", models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name="FloorSheet",
        ),
        migrations.DeleteModel(
            name="ListedSecurities",
        ),
        migrations.RenameField(
            model_name="marketsummary",
            old_name="total_scripts_traded",
            new_name="traded_scrips",
        ),
        migrations.RemoveField(
            model_name="marketsummary",
            name="date",
        ),
        migrations.RemoveField(
            model_name="marketsummary",
            name="nepse_index",
        ),
        migrations.RemoveField(
            model_name="marketsummary",
            name="sensitive_index",
        ),
        migrations.AddField(
            model_name="marketsummary",
            name="business_date",
            field=models.DateField(default="2024-01-01"),
        ),
        migrations.AlterField(
            model_name="todaysprices",
            name="close_price",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name="todaysprices",
            name="fifty_two_weeks_high",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name="todaysprices",
            name="fifty_two_weeks_low",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name="todaysprices",
            name="high_price",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name="todaysprices",
            name="last_updated_price",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name="todaysprices",
            name="low_price",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name="todaysprices",
            name="open_price",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name="todaysprices",
            name="previous_day_close_price",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name="todaysprices",
            name="total_traded_value",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
