# Generated by Django 5.1.1 on 2024-10-06 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_allsecurities_brokerdata_liveindices_livestock_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="allsecurities",
            table="all_securities",
        ),
        migrations.AlterModelTable(
            name="brokerdata",
            table="broker_data",
        ),
        migrations.AlterModelTable(
            name="liveindices",
            table="live_indices",
        ),
        migrations.AlterModelTable(
            name="livestock",
            table="live_stock",
        ),
        migrations.AlterModelTable(
            name="marketcap",
            table="market_cap",
        ),
        migrations.AlterModelTable(
            name="marketsummary",
            table="market_summary",
        ),
        migrations.AlterModelTable(
            name="nepallistedsecurities",
            table="nepal_listed_securities_data",
        ),
        migrations.AlterModelTable(
            name="sectorwisesummary",
            table="sectorwise_summary",
        ),
        migrations.AlterModelTable(
            name="todaysprices",
            table="todays_prices",
        ),
        migrations.AlterModelTable(
            name="topgainer",
            table="top_gainers",
        ),
        migrations.AlterModelTable(
            name="toploser",
            table="top_losers",
        ),
        migrations.AlterModelTable(
            name="toptrades",
            table="top_trades",
        ),
        migrations.AlterModelTable(
            name="toptransaction",
            table="top_transactions",
        ),
        migrations.AlterModelTable(
            name="topturnover",
            table="top_turnover",
        ),
        migrations.AlterModelTable(
            name="tradingaverage",
            table="trading_average",
        ),
    ]
