# Generated by Django 5.1.1 on 2024-10-06 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_allsecurities_table_alter_brokerdata_table_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="allsecurities",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="brokerdata",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="liveindices",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="livestock",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="marketcap",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="marketsummary",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="nepallistedsecurities",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="sectorwisesummary",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="todaysprices",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="topgainer",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="toploser",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="toptrades",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="toptransaction",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="topturnover",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="tradingaverage",
            options={"managed": False},
        ),
    ]
