# Generated by Django 5.1.1 on 2024-10-08 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_allsecurities_options_alter_brokerdata_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FloorSheet",
            fields=[
                ("SN", models.TextField(primary_key=True, serialize=False)),
                ("Contract_No", models.TextField(db_column="Contract No.")),
                ("stockSymbol", models.TextField(db_column="Stock Symbol")),
                ("Buyer", models.DecimalField(decimal_places=2, max_digits=20)),
                ("Seller", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "Rate",
                    models.DecimalField(
                        db_column="Rate (Rs)", decimal_places=2, max_digits=20
                    ),
                ),
                (
                    "Amount",
                    models.DecimalField(
                        db_column="Amount (Rs)", decimal_places=2, max_digits=20
                    ),
                ),
            ],
            options={
                "db_table": "floorsheet_data",
                "managed": False,
            },
        ),
    ]
