# Generated by Django 5.1.1 on 2024-10-17 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="weeklyreport",
            table="weekly_report",
        ),
    ]
