# Generated by Django 5.1.1 on 2024-10-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_weeklyreport_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnualReport",
            fields=[
                ("SN", models.BigIntegerField(primary_key=True, serialize=False)),
                ("Name", models.TextField()),
                ("Description", models.TextField()),
                ("publishedDate", models.TextField(db_column="Published Date")),
                ("fileLink", models.TextField(db_column="File Link")),
            ],
            options={
                "db_table": "annual_reports",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MonthlyReport",
            fields=[
                ("SN", models.BigIntegerField(primary_key=True, serialize=False)),
                ("Name", models.TextField()),
                ("Description", models.TextField()),
                ("publishedDate", models.TextField(db_column="Published Date")),
                ("fileLink", models.TextField(db_column="File Link")),
            ],
            options={
                "db_table": "monthly_reports",
                "managed": False,
            },
        ),
    ]
