# Generated by Django 5.1.1 on 2024-10-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_agmreport_classificationoflistedcompany"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketTopGainer",
            fields=[
                (
                    "symbol",
                    models.TextField(max_length=20, primary_key=True, serialize=False),
                ),
                ("ltp", models.DecimalField(decimal_places=2, max_digits=20)),
                ("pointChange", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "percentageChange",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
            ],
            options={
                "db_table": "top_gainers",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MarketTopLoser",
            fields=[
                (
                    "symbol",
                    models.TextField(max_length=20, primary_key=True, serialize=False),
                ),
                ("ltp", models.DecimalField(decimal_places=2, max_digits=20)),
                ("pointChange", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "percentageChange",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
            ],
            options={
                "db_table": "top_losers",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MarketTopTrades",
            fields=[
                (
                    "symbol",
                    models.TextField(max_length=20, primary_key=True, serialize=False),
                ),
                ("shareTraded", models.BigIntegerField()),
                ("closingPrice", models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                "db_table": "top_trades",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MarketTopTransaction",
            fields=[
                (
                    "securityId",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("totalTrades", models.BigIntegerField()),
                (
                    "lastTradedPrice",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                ("symbol", models.TextField(max_length=20)),
            ],
            options={
                "db_table": "top_transactions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MarketTopTurnover",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=20)),
                ("turnover", models.DecimalField(decimal_places=2, max_digits=20)),
                ("closingPrice", models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                "db_table": "top_turnover",
                "managed": False,
            },
        ),
    ]
